# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a363e5104f856244e56d95fae20a4566c7be0515639772062927490cd11b7984a5398560df5486692f314bd88398d8f886927d3c1e45dc7f196a9f0927c582c2

test:
  secret_key_base: 97f5e972aaa29c4d35646a72d6ef63c3fc7f108d5c094a2f1014b6abc1fc68dab9fd1d27d94e7f44d8d2b2a46a700b9f3ac12f8854a6fc49bf0b490b542d0e1e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
